apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-staging
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-staging
    app.kubernetes.io/part-of: partner-catalog-staging
  name: partner-catalog-staging
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-staging
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-staging
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-jsmid-tenant/partner-catalog-staging/partner-catalog-staging@sha256:30321ee70c6602c1794b279a76fe6f397e7dda23917b8d46605db0e4bce6a215
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
